Add missing type checks to interop container listener (#1747)
```
java.lang.IllegalArgumentException: Required value was null.
	at androidx.compose.ui.viewinterop.SwingInteropContainer.getClipRectForComponent(SwingInteropContainer.desktop.kt:247)
	at androidx.compose.ui.scene.ComposeSceneMediator$containerListener$1.addClipComponent(ComposeSceneMediator.desktop.kt:200)
	at androidx.compose.ui.scene.ComposeSceneMediator$containerListener$1.componentAdded(ComposeSceneMediator.desktop.kt:189)
	...
	at java.desktop/java.awt.Container.add(Container.java:1033)
	at androidx.compose.ui.scene.SwingComposeSceneLayer.<init>(SwingComposeSceneLayer.desktop.kt:122)
	at androidx.compose.ui.scene.ComposeContainer.createPlatformLayer(ComposeContainer.desktop.kt:396)
```

## Release Notes
### Fixes - Desktop
- Fix possible exception during `Dialog`/`Popup` creation in case of
`compose.layers.type=COMPONENT` and pointing `windowContainer` to
`ComposePanel` itself